### PR TITLE
Fixes Wrong id validation #28 issue.

### PR DESCRIPTION
**Pull request by SezginEge**

### CODE REVIEW

**Comment by ilkayilknur** [comment]
@SezginEge /management/storage/assets.ts id validations need to be reviewed.

**Comment by SezginEge** [comment]
@ilkayilknur What is bound value of assetId?

**Comment by ilkayilknur** [comment]
@SezginEge asset must be greater than 0.

**Comment by SezginEge** [comment]
@ilkayilknur Updated.

**Pull request merged**
